### ISSUE TITLE
[feature] Home화면 UI 구현 

### ISSUE THREAD

**Issue by ha01032** [livarter/android#2]
## Issue: Feature
메인배너 추가
카테고리 버튼 추가
베스트 버튼 추가
베스트 목록 추가
브랜드 버튼 추가

## Description
메인배너기능 - ViewPager2와 Thread로 자동으로 움직이게 구현
버튼 - LinearLayout으로 구성/ 각각의 조회필터로 연결
베스트목록 - RecyclerView-GridLayout으로 4개 추가(Spring 연동)/ 각각의 Detail로 연결

## Todo
- [x] 메인배너 만들기
- [x] 카테고리 버튼 만들기
- [x] 베스트 버튼 만들기
- [x] 베스트 상품목록 만들기
- [x] 브랜드 버튼 만들기
