### ISSUE TITLE
메인화면(MainActivity) 작업

### ISSUE THREAD

**Issue by ha01032** [livarter/android#21]
## Issue: Feature
MainFragment의 메뉴 및 이동 로직 설정

## Description
메뉴 기능 - 메뉴를 눌렀을때 Fragment 전환되도록 함
뒤로가기 경로 설정 - HomeFragment를 제외하고 나머지를 뒤로가기를 했을때 HomeFragment로 이동하게 설정
Activity onDestroy설정 - HomeFragment에서 뒤로갈때 두번 뒤로가기를 해야 앱이 꺼지도록 설정

## Todo
- [x] 메뉴간 Fragment 전환
- [x] 뒤로가기 경로 설정
- [x] HomeFragment에서 뒤로가기 경로 설정
