### ISSUE TITLE
추가 기능 구현 

### ISSUE THREAD

**Issue by osy9757** [livarter/android#40]
## Issue: Feature
추가 기능 구현  순서(순위)

## Description
설명 작성하세요.

## Todo
- [x] collections 이미지
- [x] 해시태그 #추가
- [x] products 테이블 category 채우기
- [x] brand와 설명
- [x] 프래그먼트 만들기
- [x] 여수 희망 페이지 만들기
- [x] search bottom nav bar
- [x] style 수정하기
- [x] 무한스크롤 및 페이지네이션

--------------
## Bug
- [x] search에서 sorting option 적용시 브랜드 없어지는거 수정 
- [x] db 에서 수정일, 판매량, 조회수 수정 필요
- [x] search에서 검색시 브랜드 클릭 이벤트 삭제

## ETC
기타사항
