### ISSUE TITLE
마이페이지 UI 수정 사항

### ISSUE THREAD

**Issue by sooyoungh** [livarter/android#54]
## Issue: Feature
- UI 수정 사항

## Todo
- [X] 나의 정보 조회 간격 조정 및 이미지 크기 조정
- [X] 팝업창 디자인 수정
- [X] 마이페이지 폰트 크기/색상 일괄 수정
- [ ] 멤버십 카드 디자인
- [ ] 두번 째 탭 뱃지 간격 조정
- [ ] 세번 째 탭 디자인 및 요소 추가

## ETC
기타사항
