### ISSUE TITLE
Search 페이지 구현

### ISSUE THREAD

**Issue by osy9757** [livarter/android#7]
## Issue: Feature

조건들을 통한 검색 기능 구현

## Description
검색 - 검색어, 브랜드, 해시태그, 정렬기준을 통한 Product 검색
기능 - 각 인자를 입력할 때마다 검색을 통해 아래 물품 결과 변경, 
          스크롤을 통해 엔드포인트에 닿을 때마다 이벤트를 통해 페이지를 추가후 다음 페이지 Product 전달을 통해 무한 스크롤 구현

## Todo
- [x] android, backend 파라미터에 한글 있을때 인코딩되어 전송 하는 부분 해결
- [x] Product 출력 부분 Recycling View 로 수정
- [x] 브랜드 부분 Recycling View로 수정
- [x] 해시태그 텍스트 동적 할당 및 Recycling View로 수정
- [x] sorting dropdown menu 구현
- [x] sorting 쿼리에 추가
- [x] 스크롤 엔드포인트 이벤트 생성
- [x] 엔드포인트 이벤트 시 페이지 증가후 쿼리 파라미터 전송 기능 추가
- [x] 무한 스크롤 라이브러리 구현

------- 추가 -------------
- [x] 브랜드 클릭시 식별할만한 이벤트
- [x] Search에서 뒤로가기 클릭 기능 구현
- [x] 이미 클릭한거 재클릭할시 삭제하는 기능 추가
- [x] SearchFragement에서 상품정보 DetailFragment로 전달
- [x] 브랜드, 해시태그 클릭시 텍스트 스타일 번경
